parser: babel-eslint
extends:
  - airbnb
  - prettier
rules:
  eqeqeq: ['error', 'allow-null']
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-use-before-define: off
  no-multi-spaces: off
  no-nested-ternary: off
  no-cond-assign: ['error', 'except-parens']
  no-underscore-dangle: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-continue: off
  no-restricted-properties: off
  new-cap: off
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
      mode: 'minimum'
  object-property-newline: off
  class-methods-use-this: off
  arrow-parens: off
  camelcase: off
  prefer-destructuring: off
  no-restricted-globals: off
  lines-between-class-members: off
  no-irregular-whitespace: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: true
      optionalDependencies: false
  import/prefer-default-export: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/href-no-hash: off
  jsx-a11y/label-has-for: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/click-events-have-key-events: off
